name: Deploy

on:
  workflow_dispatch:
    inputs:
      repo:
        type: choice
        description: Publish to which repository
        default: snapshot
        required: true
        options:
          - snapshot
          - staging

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  snapshot:
    if: ${{ github.event.inputs.repo == 'snapshot' }}
    runs-on: macos-latest
    env:
      ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
      ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
      ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
      versionSuffix: SNAPSHOT
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: ./.github/workflows/setup-gradle

      - name: Publish to Central Portal Snapshots
        run: ./gradlew publishAllPublicationsToMavenCentralRepository

  staging:
    if: ${{ github.event.inputs.repo == 'staging' }}
    runs-on: macos-latest
    env:
      ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
      ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
      ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: ./.github/workflows/setup-gradle

      - name: Publish to Central Portal
        run: ./gradlew publishToMavenCentral

  docs:
    runs-on: ubuntu-latest
    needs: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: ./.github/workflows/setup-gradle

      - name: Dokka
        run: ./gradlew :dokkaGenerate

      - name: Upload Dokka docs to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ github.workspace }}/build/dokka/html

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
